services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    PanKrok\ShoperAppstoreBundle\:
        resource: '../src/'
        exclude:
            - '../src/Controller/API/'
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Events/'
            - '../src/Exception/'
            - '../src/Maker/'
            - '../src/Model/'
            - '../src/ShoperAppstoreBundle.php'
